### ISSUE TITLE
Gnome 47 support

### ISSUE THREAD

**Issue by jspitz** [zeners/gnome-shell-teatime#9]
Seems that at least the [Clutter.Color](https://gjs.guide/extensions/upgrading/gnome-shell-47.html#clutter-color) change needs to be addressed.

**Comment by zeners** [comment]
which elements / lines do you mean?

**Comment by jspitz** [comment]
I only see now that you already addressed this in 547113d9985ca2e3. No idea why that escaped me. Sorry for the noise!

**Comment by zeners** [comment]
@jspitz please be aware that current master IS NOT available on extensions.gnome.org, because i wait for gnome-shell 47 is available for me. There are little difference between master and branch teatimer (which reflect extensions.gnome.org).

**Comment by jspitz** [comment]
@zeners I have installed the extension now manually from this repo (master) and it works perfectly well with GNOME 47 AFAICT.

**Comment by jspitz** [comment]
@zeners Do you happen to have GNOME 47 available meanwhile? GNOME 48 is around the corner already ;-)

**Comment by zeners** [comment]
@jspitz yes, looking for a spare time for testing and packaging

**Comment by zeners** [comment]
updated and accepted, sry for the delay
